### PR TITLE
Added new IPs and referrer

### PR DESCRIPTION
**Pull request by jswelker**
Hi,

I just discovered this project and would like to contribute. At the University of Central Missouri, I have been maintaining my own blacklist for a few years. I have a few dozen IPs and another referrer host to add. I also put together a simple spreadsheet to help dedupe my list from yours and generate the directives. You can take that or leave it.

### CODE REVIEW

**Comment by prbutler** [comment]
Thanks for contributing, this is great! Let me give them a review before I merge. I know I saw at least 1 IP belonging to a university and as a general rule I try not to include those in the blacklist, but encourage to reach out to other institutions and report abuse.

**Comment by prbutler** [comment]
I brought your edits down to my local copy, merged them with my list of new IPs, removed the IPs below that belong to other universities, then added the new additions to the master files, de-duped, and committed the changes to the master branch. I am new to Git so there may likely be an easier method to make these changes, but this worked OK for me this time. Thanks again for your contribution! to the project 

West China University of Medical Sciences
222.196.134.198

University of Texas at El Paso
129.108.148.23
129.108.148.36

Washington State University
134.121.181.214

University of Missouri
198.209.66.1

Tianjin University
202.113.11.150

Shanghai University
202.120.118.140

Capital University of Medical Sciences
202.204.188.173

**Comment by moorereason** [comment]
@prbutler,
First, thanks for maintaining this project.  I work at a small university that benefits from your labors!

My suggestion for the future would be to merge contributions in such a way that you don't lose the attribution in the commit logs (either have the author clean up the PR or you clean it up locally).  That way they are listed as a contributor to the project, which is a small but important reward for open collaboration.

**Comment by jswelker** [comment]
Thanks for letting me contribute. I will post more in the future. I've
already got some more just in the few days since I sent that last round.

**Pull request closed without merging**
